all:
  children:
    routers:
      vars:
        ansible_become: 'true'
        ansible_become_method: enable
        ansible_become_password: '!Qazplm#77'
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.ios.ios
        ansible_password: '!Qazplm#77'
        ansible_user: tkcrabtree
      children:
        csr_group:
          hosts:
            r2:
              ansible_host: 192.168.220.221
        vios_group:
          hosts:
            r1:
              ansible_host: 192.168.220.220
              ansible_ssh_private_key_file: /home/tkcrabtree/.ssh/id_rsa
              ansible_user: ansible_admin
    ungrouped:
      hosts:
        local_test:
          ansible_connection: local
